### ISSUE TITLE
Error Despite Correct Credentials

### ISSUE THREAD

**Issue by kiddmary** [avpreserve/fixity#16]
Hi,

I just installed Fixity and was configuring my Sender Email credentials.  I am using the default SMTP Server/Port/Encryption Method settings (smtp.gmail.com, 587, TLS Protocols).  When I first entered in my gmail Email Address and Password, I received a "Sign-in attempt prevented".  However, I was able to verify that the sign-in attempt was legit by reviewing and marking the sign-in attempt as "Me" through Gmail's "Recently used devices" settings.

I am not longer getting a warning message from Gmail: however, when I click "Check Credentials" I receive the error message:
Fixity was unable to send email from the provided account.
*Please ensure that you are connected to the Internet.
*Please ensure that your email credentials are correct.

I have Internet enabled and my credentials are correct (I copy and pasted my email/password from Notepad into both Fixity and Gmail).

Any help would be appreciated.

Thanks,
MK

**Comment by ashamansavage** [comment]
I am having the exact same issue with gmail. I originally tried relaying through my Exchange server, and then my sendmail server. Receiving the same error as stated by kiddmary for all scenarios.

**Comment by bertramlyons** [comment]
Hi kiddmary and ashamansavage, have you updated your gmail preferences so that it will allow 3rd party apps to send emails?

Gmail has a default setting that disallows external apps to make use of gmail independently. As a gmail user, you must change your preferences before gmail will allow a third-party app to use your email account without you. Login to gmail. Then select "my account" -> "sign in & security" -> "connected apps & sites" -> “allow less secure apps: On".

That may fix your problems. Please let us know if not.

Thanks - AVP
